version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8 # Si es necesario para algún script de soporte
    commands:
      - echo Installing Terraform...
      - curl -LO https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
      - unzip terraform_1.0.0_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version

  pre_build:
    commands:
      - echo Initializing Terraform...
      - terraform init

  build:
    commands:
      - echo Applying Terraform configuration...
      - terraform apply -auto-approve

artifacts:
  files:
    - '**/*'
  discard-paths: yes
